### ISSUE TITLE
Make some changes to fix the header.

### ISSUE THREAD

**Issue by josephtkim** [SnazofSnaz/Tea-Cozy#2]
Replace these lines
https://github.com/SnazofSnaz/Tea-Cozy/blob/master/index.html#L9-L21

with

```html
      <header class="flex-container">
         <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-tea-cozy-logo.png" />
         <nav>
            <span><a href="#mission">Mission</a></span>
            <span><a href="#store">Featured Tea</a></span>
            <span><a href="#locations">Locations</a></span>
         </nav>
      </header>
```

and replace these lines
https://github.com/SnazofSnaz/Tea-Cozy/blob/master/style.css#L12-L33

with

```css
/* Header */
header {
    position: fixed;
    z-index: 1;
    align-items: center;
    width: 100%;
    height: 69px;
    border-bottom: 1px solid seashell;
    background-color: black;
}
header img {
    height: 50px;
    padding-left: 10px;
}
nav {
    text-align: right;
    flex-grow: 1;
}
nav span {
    display: inline-block;
    padding: 20px 10px;
}
header {
    position: fixed;
    background-color: black;
    width: 100%;
    height: 69px;
    display: flex;
    z-index: 1;
    height: auto;
    width: 100%;
    text-align: center;
    border-bottom: 1px solid seashell;
}
```
