### ISSUE TITLE
More changes - add the main section to your code.

### ISSUE THREAD

**Issue by josephtkim** [SnazofSnaz/Tea-Cozy#3]
For this code
https://github.com/SnazofSnaz/Tea-Cozy/blob/master/index.html#L22-L76

surround it with a div element with the class 'main',

```html
<div class="main">
 <!-- Place all the code here -->
</div>
```

Add this code in your CSS:

```css
/* Main Section */
.main {
    padding-top: 69px;    
    opacity: 0.9;
    width: 1200px;
    margin: auto;
}
.flex-container {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
}
```
