### ISSUE TITLE
Make changes to the location section.

### ISSUE THREAD

**Issue by josephtkim** [SnazofSnaz/Tea-Cozy#4]
To fix the locations section, change the code on these lines 
https://github.com/SnazofSnaz/Tea-Cozy/blob/master/index.html#L62-L76
to

```html
         <div id="locations">
            <h2>Locations</h2>
            <div class="flex-container locations">
               <div class="location">
                  <h3>Downtown</h3>
                  <p>384 West 4th St</p>
                  <p>Suite 108</p>
                  <p>Portland, Maine</p>
               </div>
               <div class="location">
                  <h3>East Bayside</h3>
                  <p>3433 Phisherman's Avenue</p>
                  <p>(Northwest Corner)</p>
                  <p>Portland, Maine</p>
               </div>
               <div class="location">
                  <h3>Oakdale</h3>
                  <p>515 Crescent Avenue</p>
                  <p>Second Floor</p>
                  <p>Portland, Maine</p>
               </div>
            </div>
         </div>
```

Replace the code on these lines
https://github.com/SnazofSnaz/Tea-Cozy/blob/master/style.css#L109-L143
with

```css
/* Location Section */

.flex-container.locations {
    padding-top: 5px;
}
#locations {
    background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-locations-background.jpg");
    height: 500px;
    padding-top: 70px;
}
#locations .flex-container {
    margin: auto;
    width: 1100px;
}
.location {
    flex-basis: 280px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    padding: 10px;
    margin: 5px 20px;
    opacity: 1.0;
    background-color: black;
}
```
